# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_input1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 375)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 691, 391))
        self.frame.setStyleSheet("background-color: #FFFFFF;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(500, 440, 101, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 127, 255);\n"
"    border-radius: 10px;\n"
"    color:#ffffff;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 181, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 127, 255); */\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(750, 30, 171, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setStyleSheet("image: url(:/newPrefix/xampp/htdocs/kumpulinTugas/kumpulin/src/Images/KM.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setStyleSheet("image: url(:/newPrefix/xampp/htdocs/kumpulinTugas/kumpulin/src/Images/unmul.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setStyleSheet("image: url(:/newPrefix/xampp/htdocs/kumpulinTugas/kumpulin/src/Images/ICON.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 444, 161, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: rgb(75, 75, 75);\n"
"font-size: 15px;\n"
"text-decoration:underline;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   color: rgb(179, 179, 179); /* Warna latar belakang saat hover */\n"
"}\n"
"\n"
"/* QPushButton Pressed State */\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 0, 0); /* Warna latar belakang saat tombol ditekan */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 110, 251, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 230, 251, 88))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_10.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_10.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:13px;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_10.addWidget(self.lineEdit_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 330, 51, 17))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 90, 231, 231))
        self.label.setStyleSheet("image: url(:/newPrefix/coffe.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(170, 40, 261, 31))
        self.lineEdit.setStyleSheet("font: 63 24pt \"Open Sans Semibold\";\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText(_translate("Form", "Lihat hasil Pengumpulan"))
        self.lineEdit_3.setText(_translate("Form", "Nama:"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.lineEdit_4.setText(_translate("Form", "Telfon:"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "NIM"))
        self.lineEdit_5.setText(_translate("Form", "Email:"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "URL Github"))
        self.lineEdit_6.setText(_translate("Form", "Alamat:"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.lineEdit_7.setText(_translate("Form", "Pesanan:"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "NIM"))
        self.lineEdit_8.setText(_translate("Form", "Jumlah:"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "URL Github"))
        self.pushButton_3.setText(_translate("Form", "SUBMIT"))
        self.lineEdit.setText(_translate("Form", "COFFE SHOP PUTRI\'S"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
